{{- if .Values.istio.virtualService.enabled -}}
{{- $fullName := include "pihole.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: {{ $fullName }}
spec:
 hosts:
 - {{ .Values.istio.gateway.hostName  }}
 gateways:
 - {{ .Release.Namespace }}/{{ $fullName }}
 http:
 - match:
   route:
   - destination:
       port:
         number: {{ .Values.tcpService.port | default 8080 }}
       host: {{ include "pihole.fullname" . }}-tcp.{{ .Release.Namespace}}.svc.cluster.local
{{- end }}
