{{- $secret := (lookup "v1" "Secret" .Release.Namespace "pihole-secret") -}}
apiVersion: v1
kind: Secret
metadata:
 name: pihole-secret
 labels:
   {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
{{ if $secret -}}
data:
  password: {{ $secret.data.password }}
{{ else -}}
data:
  password:  {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}