commonLabels:
  app: pihole

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 75Mi

istio:
  gateway:
    enabled: true
    selector: ingressgateway
    tls:
      enabled: true
      credentialName: pihole-tls
    hostName: pihole.donthurt.us
  virtualService:
    enabled: true
    retries: {}
     # attempts: 3
     # perTryTimeout: 1s
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100

nodeSelector:
  kubernetes.io/os: linux
  storage-tier: ssd

tolerations:
  - key: 'storage'
    operator: 'Equal'
    value: 'ssd'
    effect: 'NoSchedule'
