namespace: pihole

helm:
  releaseName: pihole
  valuesFiles:
    - values.yaml
    - values/k3s-rpi-values.yaml

rolloutStrategy:
  partitions:
  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
        clusterName: k3s-rpi
